name: Deploy to Firebase

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Build'
        description: 'Release Notes'

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew Executable
        run: chmod +x ./gradlew

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      - name: Verify Debug APK File
        run: |
          if [ ! -f app/build/outputs/apk/debug/app-debug.apk ]; then
            echo "Debug APK file not found."
            exit 1
          fi

      - name: Upload Debug APK to Firebase App Distribution
        if: success()
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{ github.event.inputs.release_notes }}

      - name: Assemble Release APK
        run: ./gradlew assembleRelease
