name: Release Workflow

# Step 1: Choosing which branches 
on:
  push:
    branches:
      - main
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Build with Gradle Wrapper
        run: ./gradlew build

# Step 2: Decode Android config file
