name: Pull Workflow

# Step 1: Choosing which branches 
on:
  pull_request:
   
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name:  Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run the spotlessApply command to format our files
        run: ./gradlew spotlessApply
      - name: Run ktlint
        run: ./gradlew ktlintCheck
      - name: Run Build with Gradle Wrapper
        run: ./gradlew build

# Step 2: Decode Android config file
